services:
  mysql:
    image: mysql:8.0
    container_name: mysql_shift
    restart: always
    environment:
      MYSQL_DATABASE: shift_db
      MYSQL_ROOT_PASSWORD: 123456

    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
  
jwt:
  secret: ${JWT_SECRET}

