services:
  mysql:
    image: mysql:8.0
    container_name: mysql_shift
    restart: always
    environment:
      MYSQL_DATABASE: shift_db
      MYSQL_ROOT_PASSWORD: 123456

    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
  # spring-app:
  #   build: .
  #   container_name: spring-app
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_PROFILES_ACTIVE: docker
  #   command: >
  #     sh -c "java -jar /app.jar"

