spring:
  datasource:
    url: jdbc:mysql://localhost:3308/shift_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: admin
      password: admin

server:
  port: 8080
  servlet:
    context-path: /


jwt:
  secret: ${JWT_SECRET}